source 'https://rubygems.org'
gem 'sqlite3'
gem 'base32'
#gem "json"
#gem "stellar-base" ,"0.6.1"
gem "stellar-base"
gem "pg"
gem "em-websocket"
gem "em-websocket-client"
gem "faraday"
gem "faraday_middleware"
gem 'rest-client'



